# Exemplo de arquivo docker-compose.yml
# Altere todos os valores que estão com # para os valores do seu projeto
services:
  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER} # Altere o usuário do banco de dados
      POSTGRES_PASSWORD: ${DB_PASS} # Altere a senha do banco de dados
      POSTGRES_DB: ${DB_NAME} # Altere o nome do banco de dados
    ports:
      - "${HOST_PORT_DB:-4000}:5432" # Altere a primeira porta que deseja expor
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      retries: 5
    networks:
      - aiatende-network

  conversions:
    build: .
    command: >
      sh -c "
      npm run migrate &&
      npm run start"
    working_dir: /home/node/app
    depends_on:
      database:
        condition: service_healthy
    environment:
      - TZ=${GENERIC_TIMEZONE} # Fuso horário da aplicação
      - KOMMO_AUTH=${KOMMO_AUTH} # Token de acesso do Kommo
      - KOMMO_URL=${KOMMO_URL} # URL do Kommo
      - DB_URL=postgres://${DB_USER}:${DB_PASS}@database:5432/${DB_NAME}?schema=tracking_data # URL de conexão com o banco de dados (postgres://DB_USER:DB_PASS@DB_HOST:DB_PORT/DB_NAME)
      - GA4_MEASUREMENT_ID=${GA4_MEASUREMENT_ID} # ID de medição do GA4
      - GA4_API_SECRET=${GA4_API_SECRET} # Segredo da API do GA4
      - WHATSAPP_NUMBER=${WHATSAPP_NUMBER} # Número do WhatsApp
    ports:
      - "${HOST_PORT_CONVERSIONS:-2000}:3000" # Altere a primeira porta para a que deseja expor
    networks:
      - aiatende-network

volumes:
  data:

networks:
  aiatende-network:
    driver: bridge